### ISSUE TITLE
nixos-hardware won't build with new linux kernal 6.12.19

### ISSUE THREAD

**Issue by Steven-S1020** [NixOS/nixos-hardware#1674]
I recently update my and I kept getting an error that pointed back to some rust code. I proceeded to go back to a working build and update all of my flake inputs besides nixos-hardware and the issue still persisted. Finally I commented out my nixos-hardware flake input and the new Linux Kernel and my system built just fine. After I tried adding nixos-hardware back but I still received the same error as before that points to some Rust code. Bellow I will put my flake.lock file for the build that fails and the error that gets returned.

Error Output After Build:
```
┏━ 2 Errors: 
┃ error: Cannot build '/nix/store/zsyr96fvmyis8bcfq8gq4f80wv1fz603-nixos-system-Azami-25.11.20251111.9da7f1c.drv'.
┃        Reason: 1 dependency failed.
┃        Output paths:
┃          /nix/store/1ifl5mwqlj8b6ff7k1vfn14l8xsxvhvc-nixos-system-Azami-25.11.20251111.9da7f1c
┃ error: Cannot build '/nix/store/5l3ga48dksza7k4z559km2ny05arfs4m-linux-6.12.19.drv'.
┃        Reason: builder failed with exit code 2.
┃        Output paths:
┃          /nix/store/mq2q6q3vdywm1yy1r47w9rhhfidzqssb-linux-6.12.19
┃          /nix/store/w8sp2rlil21zsbrmc1kr033fls1ayiy3-linux-6.12.19-modules
┃          /nix/store/zxy7azdpv07rzh6cmg0441fmac5sym1s-linux-6.12.19-dev
┃        Last 25 log lines:
┃        >
┃        > error[E0700]: hidden type for `impl fmt::Display` captures lifetime that does not appear in bounds
┃        >    --> /core/src/ffi/c_str.rs:659:9
┃        >     |
┃        > 658 |     pub fn display(&self) -> impl fmt::Display {
┃        >     |                    -----     ----------------- opaque type defined here
┃        >     |                    |
┃        >     |                    hidden type `&ByteStr` captures the anonymous lifetime defined here
┃        > 659 |         crate::bstr::ByteStr::from_bytes(self.to_bytes())
┃        >     |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
┃        >     |
┃        > help: add a `use<...>` bound to explicitly capture `'_`
┃        >     |
┃        > 658 |     pub fn display(&self) -> impl fmt::Display + use<'_> {
┃        >     |                                                +++++++++
┃        >
┃        > error: aborting due to 6 previous errors
┃        >
┃        > Some errors have detailed explanations: E0658, E0700.
┃        > For more information about an error, try `rustc --explain E0658`.
┃        > make[3]: *** [../rust/Makefile:413: rust/core.o] Error 1
┃        > make[2]: *** [/build/linux-6.12.19/Makefile:1222: prepare] Error 2
┃        > make[1]: *** [/build/linux-6.12.19/Makefile:224: __sub-make] Error 2
┃        > make[1]: Leaving directory '/build/linux-6.12.19/build'
┃        > make: *** [Makefile:224: __sub-make] Error 2
┃        For full logs, run:
┃          nix log /nix/store/5l3ga48dksza7k4z559km2ny05arfs4m-linux-6.12.19.drv
```

flake.lock:
```
{
  "nodes": {
    "base16": {
      "inputs": {
        "fromYaml": "fromYaml"
      },
      "locked": {
        "lastModified": 1755819240,
        "narHash": "sha256-qcMhnL7aGAuFuutH4rq9fvAhCpJWVHLcHVZLtPctPlo=",
        "owner": "SenchoPens",
        "repo": "base16.nix",
        "rev": "75ed5e5e3fce37df22e49125181fa37899c3ccd6",
        "type": "github"
      },
      "original": {
        "owner": "SenchoPens",
        "repo": "base16.nix",
        "type": "github"
      }
    },
    "base16-fish": {
      "flake": false,
      "locked": {
        "lastModified": 1754405784,
        "narHash": "sha256-l9xHIy+85FN+bEo6yquq2IjD1rSg9fjfjpyGP1W8YXo=",
        "owner": "tomyun",
        "repo": "base16-fish",
        "rev": "23ae20a0093dca0d7b39d76ba2401af0ccf9c561",
        "type": "github"
      },
      "original": {
        "owner": "tomyun",
        "repo": "base16-fish",
        "rev": "23ae20a0093dca0d7b39d76ba2401af0ccf9c561",
        "type": "github"
      }
    },
    "base16-helix": {
      "flake": false,
      "locked": {
        "lastModified": 1752979451,
        "narHash": "sha256-0CQM+FkYy0fOO/sMGhOoNL80ftsAzYCg9VhIrodqusM=",
        "owner": "tinted-theming",
        "repo": "base16-helix",
        "rev": "27cf1e66e50abc622fb76a3019012dc07c678fac",
        "type": "github"
      },
      "original": {
        "owner": "tinted-theming",
        "repo": "base16-helix",
        "type": "github"
      }
    },
    "base16-vim": {
      "flake": false,
      "locked": {
        "lastModified": 1732806396,
        "narHash": "sha256-e0bpPySdJf0F68Ndanwm+KWHgQiZ0s7liLhvJSWDNsA=",
        "owner": "tinted-theming",
        "repo": "base16-vim",
        "rev": "577fe8125d74ff456cf942c733a85d769afe58b7",
        "type": "github"
      },
      "original": {
        "owner": "tinted-theming",
        "repo": "base16-vim",
        "rev": "577fe8125d74ff456cf942c733a85d769afe58b7",
        "type": "github"
      }
    },
    "firefox-gnome-theme": {
      "flake": false,
      "locked": {
        "lastModified": 1758112371,
        "narHash": "sha256-lizRM2pj6PHrR25yimjyFn04OS4wcdbc38DCdBVa2rk=",
        "owner": "rafaelmardojai",
        "repo": "firefox-gnome-theme",
        "rev": "0909cfe4a2af8d358ad13b20246a350e14c2473d",
        "type": "github"
      },
      "original": {
        "owner": "rafaelmardojai",
        "repo": "firefox-gnome-theme",
        "type": "github"
      }
    },
    "flake-parts": {
      "inputs": {
        "nixpkgs-lib": [
          "stylix",
          "nixpkgs"
        ]
      },
      "locked": {
        "lastModified": 1756770412,
        "narHash": "sha256-+uWLQZccFHwqpGqr2Yt5VsW/PbeJVTn9Dk6SHWhNRPw=",
        "owner": "hercules-ci",
        "repo": "flake-parts",
        "rev": "4524271976b625a4a605beefd893f270620fd751",
        "type": "github"
      },
      "original": {
        "owner": "hercules-ci",
        "repo": "flake-parts",
        "type": "github"
      }
    },
    "flake-utils": {
      "inputs": {
        "systems": "systems"
      },
      "locked": {
        "lastModified": 1731533236,
        "narHash": "sha256-l0KFg5HjrsfsO/JpG+r7fRrqm12kzFHyUHqHCVpMMbI=",
        "owner": "numtide",
        "repo": "flake-utils",
        "rev": "11707dc2f618dd54ca8739b309ec4fc024de578b",
        "type": "github"
      },
      "original": {
        "owner": "numtide",
        "repo": "flake-utils",
        "type": "github"
      }
    },
    "fromYaml": {
      "flake": false,
      "locked": {
        "lastModified": 1731966426,
        "narHash": "sha256-lq95WydhbUTWig/JpqiB7oViTcHFP8Lv41IGtayokA8=",
        "owner": "SenchoPens",
        "repo": "fromYaml",
        "rev": "106af9e2f715e2d828df706c386a685698f3223b",
        "type": "github"
      },
      "original": {
        "owner": "SenchoPens",
        "repo": "fromYaml",
        "type": "github"
      }
    },
    "gnome-shell": {
      "flake": false,
      "locked": {
        "lastModified": 1748186689,
        "narHash": "sha256-UaD7Y9f8iuLBMGHXeJlRu6U1Ggw5B9JnkFs3enZlap0=",
        "owner": "GNOME",
        "repo": "gnome-shell",
        "rev": "8c88f917db0f1f0d80fa55206c863d3746fa18d0",
        "type": "github"
      },
      "original": {
        "owner": "GNOME",
        "ref": "48.2",
        "repo": "gnome-shell",
        "type": "github"
      }
    },
    "home-manager": {
      "inputs": {
        "nixpkgs": [
          "nixpkgs"
        ]
      },
      "locked": {
        "lastModified": 1762964643,
        "narHash": "sha256-RYHN8O/Aja59XDji6WSJZPkJpYVUfpSkyH+PEupBJqM=",
        "owner": "nix-community",
        "repo": "home-manager",
        "rev": "827f2a23373a774a8805f84ca5344654c31f354b",
        "type": "github"
      },
      "original": {
        "owner": "nix-community",
        "ref": "master",
        "repo": "home-manager",
        "type": "github"
      }
    },
    "mkdev": {
      "inputs": {
        "flake-utils": "flake-utils",
        "nixpkgs": [
          "nixpkgs"
        ]
      },
      "locked": {
        "lastModified": 1750161027,
        "narHash": "sha256-5FN5Q6MPaldUvH59nObZyca7n8BYmzh/D6rSEV/Q1UM=",
        "owner": "4jamesccraven",
        "repo": "mkdev",
        "rev": "5fcec0dbc5b65aca2e8d1f4bcee047961572daa9",
        "type": "github"
      },
      "original": {
        "owner": "4jamesccraven",
        "repo": "mkdev",
        "type": "github"
      }
    },
    "nixos-hardware": {
      "locked": {
        "lastModified": 1762847253,
        "narHash": "sha256-BWWnUUT01lPwCWUvS0p6Px5UOBFeXJ8jR+ZdLX8IbrU=",
        "owner": "NixOS",
        "repo": "nixos-hardware",
        "rev": "899dc449bc6428b9ee6b3b8f771ca2b0ef945ab9",
        "type": "github"
      },
      "original": {
        "owner": "NixOS",
        "ref": "master",
        "repo": "nixos-hardware",
        "type": "github"
      }
    },
    "nixpkgs": {
      "locked": {
        "lastModified": 1762844143,
        "narHash": "sha256-SlybxLZ1/e4T2lb1czEtWVzDCVSTvk9WLwGhmxFmBxI=",
        "owner": "nixos",
        "repo": "nixpkgs",
        "rev": "9da7f1cf7f8a6e2a7cb3001b048546c92a8258b4",
        "type": "github"
      },
      "original": {
        "owner": "nixos",
        "ref": "nixos-unstable",
        "repo": "nixpkgs",
        "type": "github"
      }
    },
    "nur": {
      "inputs": {
        "flake-parts": [
          "stylix",
          "flake-parts"
        ],
        "nixpkgs": [
          "stylix",
          "nixpkgs"
        ]
      },
      "locked": {
        "lastModified": 1758998580,
        "narHash": "sha256-VLx0z396gDCGSiowLMFz5XRO/XuNV+4EnDYjdJhHvUk=",
        "owner": "nix-community",
        "repo": "NUR",
        "rev": "ba8d9c98f5f4630bcb0e815ab456afd90c930728",
        "type": "github"
      },
      "original": {
        "owner": "nix-community",
        "repo": "NUR",
        "type": "github"
      }
    },
    "root": {
      "inputs": {
        "home-manager": "home-manager",
        "mkdev": "mkdev",
        "nixos-hardware": "nixos-hardware",
        "nixpkgs": "nixpkgs",
        "stylix": "stylix",
        "zen-browser": "zen-browser"
      }
    },
    "stylix": {
      "inputs": {
        "base16": "base16",
        "base16-fish": "base16-fish",
        "base16-helix": "base16-helix",
        "base16-vim": "base16-vim",
        "firefox-gnome-theme": "firefox-gnome-theme",
        "flake-parts": "flake-parts",
        "gnome-shell": "gnome-shell",
        "nixpkgs": [
          "nixpkgs"
        ],
        "nur": "nur",
        "systems": "systems_2",
        "tinted-foot": "tinted-foot",
        "tinted-kitty": "tinted-kitty",
        "tinted-schemes": "tinted-schemes",
        "tinted-tmux": "tinted-tmux",
        "tinted-zed": "tinted-zed"
      },
      "locked": {
        "lastModified": 1762264356,
        "narHash": "sha256-QVfC53Ri+8n3e7Ujx9kq6all3+TLBRRPRnc6No5qY5w=",
        "owner": "danth",
        "repo": "stylix",
        "rev": "647bb8dd96a206a1b79c4fd714affc88b409e10b",
        "type": "github"
      },
      "original": {
        "owner": "danth",
        "repo": "stylix",
        "type": "github"
      }
    },
    "systems": {
      "locked": {
        "lastModified": 1681028828,
        "narHash": "sha256-Vy1rq5AaRuLzOxct8nz4T6wlgyUR7zLU309k9mBC768=",
        "owner": "nix-systems",
        "repo": "default",
        "rev": "da67096a3b9bf56a91d16901293e51ba5b49a27e",
        "type": "github"
      },
      "original": {
        "owner": "nix-systems",
        "repo": "default",
        "type": "github"
      }
    },
    "systems_2": {
      "locked": {
        "lastModified": 1681028828,
        "narHash": "sha256-Vy1rq5AaRuLzOxct8nz4T6wlgyUR7zLU309k9mBC768=",
        "owner": "nix-systems",
        "repo": "default",
        "rev": "da67096a3b9bf56a91d16901293e51ba5b49a27e",
        "type": "github"
      },
      "original": {
        "owner": "nix-systems",
        "repo": "default",
        "type": "github"
      }
    },
    "tinted-foot": {
      "flake": false,
      "locked": {
        "lastModified": 1726913040,
        "narHash": "sha256-+eDZPkw7efMNUf3/Pv0EmsidqdwNJ1TaOum6k7lngDQ=",
        "owner": "tinted-theming",
        "repo": "tinted-foot",
        "rev": "fd1b924b6c45c3e4465e8a849e67ea82933fcbe4",
        "type": "github"
      },
      "original": {
        "owner": "tinted-theming",
        "repo": "tinted-foot",
        "rev": "fd1b924b6c45c3e4465e8a849e67ea82933fcbe4",
        "type": "github"
      }
    },
    "tinted-kitty": {
      "flake": false,
      "locked": {
        "lastModified": 1735730497,
        "narHash": "sha256-4KtB+FiUzIeK/4aHCKce3V9HwRvYaxX+F1edUrfgzb8=",
        "owner": "tinted-theming",
        "repo": "tinted-kitty",
        "rev": "de6f888497f2c6b2279361bfc790f164bfd0f3fa",
        "type": "github"
      },
      "original": {
        "owner": "tinted-theming",
        "repo": "tinted-kitty",
        "type": "github"
      }
    },
    "tinted-schemes": {
      "flake": false,
      "locked": {
        "lastModified": 1757716333,
        "narHash": "sha256-d4km8W7w2zCUEmPAPUoLk1NlYrGODuVa3P7St+UrqkM=",
        "owner": "tinted-theming",
        "repo": "schemes",
        "rev": "317a5e10c35825a6c905d912e480dfe8e71c7559",
        "type": "github"
      },
      "original": {
        "owner": "tinted-theming",
        "repo": "schemes",
        "type": "github"
      }
    },
    "tinted-tmux": {
      "flake": false,
      "locked": {
        "lastModified": 1757811970,
        "narHash": "sha256-n5ZJgmzGZXOD9pZdAl1OnBu3PIqD+X3vEBUGbTi4JiI=",
        "owner": "tinted-theming",
        "repo": "tinted-tmux",
        "rev": "d217ba31c846006e9e0ae70775b0ee0f00aa6b1e",
        "type": "github"
      },
      "original": {
        "owner": "tinted-theming",
        "repo": "tinted-tmux",
        "type": "github"
      }
    },
    "tinted-zed": {
      "flake": false,
      "locked": {
        "lastModified": 1757811247,
        "narHash": "sha256-4EFOUyLj85NRL3OacHoLGEo0wjiRJzfsXtR4CZWAn6w=",
        "owner": "tinted-theming",
        "repo": "base16-zed",
        "rev": "824fe0aacf82b3c26690d14e8d2cedd56e18404e",
        "type": "github"
      },
      "original": {
        "owner": "tinted-theming",
        "repo": "base16-zed",
        "type": "github"
      }
    },
    "zen-browser": {
      "inputs": {
        "nixpkgs": [
          "nixpkgs"
        ]
      },
      "locked": {
        "lastModified": 1762827415,
        "narHash": "sha256-YxPQbafcd09foVFn5yHggTZDbXsrtHVae+iwo2wGn0w=",
        "owner": "youwen5",
        "repo": "zen-browser-flake",
        "rev": "6e0ad935d9caad128d2c58b2a1ba31524c0fe7f1",
        "type": "github"
      },
      "original": {
        "owner": "youwen5",
        "repo": "zen-browser-flake",
        "type": "github"
      }
    }
  },
  "root": "root",
  "version": 7
}
```
